services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks: 
      - mern-app-network
    depends_on:
      - mongodb-service
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    networks: 
      - mern-app-network
    depends_on:
      - backend
  mongodb-service:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app-network
    volumes:
      - mongodb-volume:/var/lib/mongodb/data
networks: 
  mern-app-network:
    driver: bridge
volumes:
  mongodb-volume:
    driver: local
