services:
  backend-c:
    image: localhost:5000/backend-image
    ports:
      - "8000:8000"
    networks: 
      - mern-app-network-c
    depends_on:
      - mongo
  frontend-c:
    image: localhost:5000/frontend-image
    ports:
      - "80:80"
    networks: 
      - mern-app-network-c
  mongo:
    image: localhost:5000/mongodb-image
    ports:
      - "27017:27017"
    networks:
      - mern-app-network-c
    volumes:
      - mongodb-volume-c:/app
networks: 
  mern-app-network-c:
    driver: bridge
volumes:
  mongodb-volume-c:
    driver: local
